version: "3.8"

services:

  mongodb:
    image: mongo
    restart: "on-failure"
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_DB_CONNECTION_STRING=$MONGO_DOCKER_URI # optional for debugging via mongosh

  mongoexpress:
    image: mongo-express
    restart: "on-failure"
    ports:
      - $DB_UI_LOCAL_PORT:$DB_UI_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=$DB_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$DB_PASSWORD

volumes:
  mongodb_data: {}
